#include <bashclass/BGenerateCode.h>

void BGenerateCode::preCode() {
    std::cout << "#!/bin/bash" << std::endl << std::endl
              << "# Bash version 4+ required!" << std::endl
              << "# This code is auto generated by bashc, do not make manual changes";
}

void BGenerateCode::write(std::stringstream code) {
    std::cout << code.str() << std::endl;
}
